baseURL: https://agonzalezro.github.io
languageCode: en-us
title: // Álex Go{,5z}
theme: hello-friend
googleAnalytics: UA-35984509-1

paginate: 9999 # Let's call it infinite

params:
  rssFullText: true

  rss:
    authorName: Álex González
    authorEmail: agonzalezro@gmail.com

  defaultTheme: light
  showReadingTime: true

languages:
  en:
    dateFormatSingle: "02-01-2006" 
    dateFormatList: "02-01-2006"

    params:
      logo:
        logoText: "// Álex Go{,5z}"
